title = "ADMX configuration"

[admx]
	batch = false
	starttime = "Thu, 20 Apr 2017 11:30:00 CEST"
	endtime = "Thu, 20 Apr 2017 12:00:00 CEST"
	outdir = "/tmp/admx"
	[admx.webui]
		port = 8081
[influxdb]
    [influxdb.kieker]
        addr = "http://localhost:8086"
	    username = "root"
	    password = "root"
	    db = "kieker"
    [influxdb.k8s]
        addr = "http://localhost:8086"
	    username = "root"
	    password = "root"
	    db = "k8s"
