title = "ADMX configuration"

[admx]
	batch = true
	starttime = "Fri, 31 Mar 2017 13:10:00 GMT"
	endtime = "Fri, 31 Mar 2017 13:25:00 GMT"
	output = "/tmp/adm.json"
	[admx.webui]
		port = 8081
[influxdb]
    [influxdb.kieker]
        addr = "http://localhost:8086"
	    username = "root"
	    password = "root"
	    db = "kieker"
    [influxdb.k8s]
        addr = "http://localhost:8086"
	    username = "root"
	    password = "root"
	    db = "k8s"
