title = "ADMX configuration"

[admx]
	batch = true
	starttime = "Tue, 11 Apr 2017 13:13:00 CET"
	endtime = "Tue, 11 Apr 2017 14:20:00 CET"
	outdir = "/tmp/admx"
	[admx.webui]
		port = 8081
[influxdb]
    [influxdb.kieker]
        addr = "http://localhost:8086"
	    username = "root"
	    password = "root"
	    db = "kieker"
    [influxdb.k8s]
        addr = "http://localhost:8086"
	    username = "root"
	    password = "root"
	    db = "k8s"
